In [2]:
from src.helpers import *
from src.visualization import *
from src.Decks_Class import *
import pandas as pd
import numpy as np
import os

In [121]:
Trick_Wins, Trick_Losses, Cards_Wins, Cards_Losses = get_complete_tables()

total = np.sum(np.load('src/Decks/deck_lengths.npy'))

mask = np.asarray(Trick_Wins==0)
color_labels = ['RRR', 'RRB', 'RBR', 'RBB', 'BRR', 'BRB', 'BBR', 'BBB']

trick_win_percent = (Trick_Wins)/total
trick_loss_percent = (Trick_Losses)/total

cards_win_percent = (Cards_Wins)/total
cards_loss_percent = (Cards_Losses)/total

In [140]:
def create_graphs(win, loss, name):
    n = "{:.0e}".format(int(total))
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(26, 12))
    fig.suptitle(f'Penneys Game - {name} \n(n={n})', fontsize=24)
    
    plt.yticks(rotation=0)
    ax1 = sns.heatmap(win, 
                annot=True, mask = mask, cmap='Reds', fmt='.2%', linewidths=.5, ax=ax1)
    
    ax1.set_title('Win Percentage', fontsize=20)
    ax1.set_xlabel('Player 2', fontsize=16)
    ax1.set_ylabel('Player 1', fontsize=16)
    ax1.set_yticklabels(labels = color_labels, rotation=0, fontsize=14)
    ax1.set_xticklabels(labels = color_labels, rotation=0, fontsize=14)
    ax1.figure.axes[-1].set_ylabel('Player 1 Win Percentage', size=16)
    
    
    ax2 = sns.heatmap(loss, 
                annot=True, mask = mask, cmap='Blues', fmt='.2%', linewidths=.5, ax=ax2)
    
    ax2.set_title('Loss Percentage', fontsize=20)
    ax2.set_xlabel('Player 2', fontsize=16)
    ax2.set_ylabel('Player 1', fontsize=16)
    ax2.set_yticklabels(labels = color_labels, rotation=0, fontsize=14)
    ax2.set_xticklabels(labels = color_labels, rotation=0, fontsize=14)
    ax1.figure.axes[-1].set_ylabel('Player 1 Loss Percentage', size=16)
    
    plt.savefig(f'figures/{name}_heatmap.png')
    plt.show()

In [ ]:



n = "{:.0e}".format(int(total))
plt.figure(figsize=(10, 9))
mask = trick_win_percent.isnull()
sns.heatmap(trick_win_percent, annot=True, mask = mask, cmap='Reds', fmt='.2%', linewidths=.5, cbar_kws={'label': 'PLayer 1 Win Percentage'})
plt.title(f'Penneys Game Win Percentage Heatmap\n(n={n})')
plt.yticks(rotation=0)
plt.xlabel('Player 2')
plt.ylabel('Player 1')


plt.figure(figsize=(10, 9))
sns.heatmap(trick_loss_percent, annot=True, mask = mask, cmap='Blues', fmt='.2%',cbar_kws={'label': 'PLayer 1 Loss Percentage'})
plt.title(f'Penneys Game Loss Percentage Heatmap\n(n={total})')
plt.yticks(rotation=0)
plt.xlabel('Player 2')
plt.ylabel('Player 1')


# plt.figure(figsize=(10, 9))
# sns.heatmap(cards_win_percent, annot=True, mask = mask, cmap='Reds', fmt='.2%', cbar_kws={'label': 'PLayer 1 Win Percentage'})
# plt.title(f'Penneys Game Win Percentage Heatmap\n(n={n})')
# plt.yticks(rotation=0)
# plt.xlabel('Player 2')
# plt.ylabel('Player 1')
# plt.savefig('figures/cards_win_heatmap.png')

# plt.figure(figsize=(10, 9))
# sns.heatmap(cards_loss_percent, annot=True, mask = mask, cmap='Blues', fmt='.2%',cbar_kws={'label': 'PLayer 1 Loss Percentage'})
# plt.title(f'Penneys Game Loss Percentage Heatmap\n(n={n})')
# plt.yticks(rotation=0)
# plt.xlabel('Player 2')
# plt.ylabel('Player 1')


# plt.figure(figsize=(10, 9))
# sns.heatmap(trick_win_percent-cards_win_percent, annot=True, mask = mask, cmap='vlag', fmt='.2%',cbar_kws={'label': 'PLayer 1 Win Percentage Difference'})
# plt.title(f'Penneys Game Cards vs Tricks Win Percentage Heatmap\n(n={n})')
# plt.yticks(rotation=0)
# plt.xlabel('Player 2')
# plt.ylabel('Player 1')


# plt.figure(figsize=(10, 9))
# sns.heatmap(trick_loss_percent-cards_loss_percent, annot=True, mask = mask, cmap='vlag', fmt='.2%',cbar_kws={'label': 'PLayer 1 Loss Percentage Difference'})
# plt.title(f'Penneys Game Cards vs Tricks Loss Percentage Heatmap\n(n={n})')
# plt.yticks(rotation=0)
# plt.xlabel('Player 2')
# plt.ylabel('Player 1')


In [144]:
pick_what = pd.DataFrame(data = [[None]*5]*8, columns=['Opponent_Pick','Tricks_WinMax', 'Tricks_LossMin', 'Cards_WinMax','Cards_MinLoss'])
for i, pick in enumerate(Tricks_winp.columns):
    pick_what.loc[i, 'Opponent_Pick'] = pick
    pick_what.loc[i, 'Tricks_WinMax'] = [Tricks_winp.iloc[:,(Tricks_winp.iloc[:,i].argmax())].name, round(Tricks_winp.iloc[:,i].max(),2)]
    pick_what.loc[i, 'Tricks_LossMin'] = [Tricks_lossp.iloc[:,Tricks_lossp.iloc[:,i].argmin()].name, round(Tricks_lossp.iloc[:,i].min(),2)]
    pick_what.loc[i, 'Cards_WinMax'] = [Tricks_winp.iloc[:,(Tricks_winp.iloc[:,i].argmax())].name, round(Tricks_winp.iloc[:,i].max(),2)]
    pick_what.loc[i, 'Cards_MinLoss'] = [Tricks_lossp.iloc[:,Cards_lossp.iloc[:,i].argmin()].name, round(Cards_lossp.iloc[:,i].min(),2)]

In [147]:
pick_what

Opponent_Pick      Tricks_WinMax     Tricks_LossMin       Cards_WinMax  \
0     [0, 0, 0]  [[1, 0, 0], 0.99]   [[1, 0, 0], 0.0]  [[1, 0, 0], 0.99]   
1     [0, 0, 1]  [[1, 0, 0], 0.94]  [[1, 0, 0], 0.03]  [[1, 0, 0], 0.94]   
2     [0, 1, 0]   [[0, 0, 1], 0.8]  [[1, 1, 0], 0.11]   [[0, 0, 1], 0.8]   
3     [0, 1, 1]  [[0, 0, 1], 0.88]  [[0, 0, 1], 0.05]  [[0, 0, 1], 0.88]   
4     [1, 0, 0]  [[1, 1, 0], 0.88]  [[1, 1, 0], 0.05]  [[1, 1, 0], 0.88]   
5     [1, 0, 1]   [[1, 1, 0], 0.8]  [[0, 0, 1], 0.11]   [[1, 1, 0], 0.8]   
6     [1, 1, 0]  [[0, 1, 1], 0.94]  [[0, 1, 1], 0.03]  [[0, 1, 1], 0.94]   
7     [1, 1, 1]  [[0, 1, 1], 0.99]   [[0, 1, 1], 0.0]  [[0, 1, 1], 0.99]   

       Cards_MinLoss  
0  [[1, 1, 1], 0.49]  
1  [[1, 1, 1], 0.01]  
2  [[1, 1, 1], 0.25]  
3   [[1, 1, 1], 0.0]  
4   [[0, 0, 0], 0.0]  
5  [[0, 0, 0], 0.25]  
6  [[0, 0, 0], 0.01]  
7  [[0, 0, 0], 0.49]

NameError: name 'Cards_lossp' is not defined

In [110]:
{Tricks_winp.iloc[:,(Tricks_winp.iloc[0].argmax())].name, Tricks_winp.iloc[1].max()}

{np.float64(0.9671671958201045), '[1, 1, 1]'}

In [132]:
Tricks_winp.iloc[:1]

[0, 0, 0]  [0, 0, 1]  [0, 1, 0]  [0, 1, 1]  [1, 0, 0]  [1, 0, 1]  \
[0, 0, 0]        NaN   0.404458   0.211646   0.112528   0.001141   0.167827   

           [1, 1, 0]  [1, 1, 1]  
[0, 0, 0]   0.008326   0.325194

In [123]:
Tricks_winp

[0, 0, 0]  [0, 0, 1]  [0, 1, 0]  [0, 1, 1]  [1, 0, 0]  [1, 0, 1]  \
[0, 0, 0]        NaN   0.404458   0.211646   0.112528   0.001141   0.167827   
[0, 0, 1]   0.441164        NaN   0.801136   0.882746   0.026267   0.792212   
[0, 1, 0]   0.664728   0.116062        NaN   0.431454   0.423631   0.406318   
[0, 1, 1]   0.769601   0.051817   0.431776        NaN   0.431744   0.442256   
[1, 0, 0]   0.994828   0.935239   0.442010   0.431373        NaN   0.431489   
[1, 0, 1]   0.694413   0.113643   0.406163   0.423590   0.431691        NaN   
[1, 1, 0]   0.967368   0.409351   0.792313   0.026214   0.882873   0.801072   
[1, 1, 1]   0.325090   0.008379   0.167759   0.001110   0.112569   0.211706   

           [1, 1, 0]  [1, 1, 1]  
[0, 0, 0]   0.008326   0.325194  
[0, 0, 1]   0.409324   0.967167  
[0, 1, 0]   0.113402   0.694125  
[0, 1, 1]   0.935326   0.994855  
[1, 0, 0]   0.051800   0.769690  
[1, 0, 1]   0.116056   0.664840  
[1, 1, 0]        NaN   0.441466  
[1, 1, 1]   0.404258        NaN

In [115]:
pick_what['Opponent_Pick'][[1]]

1    None
Name: Opponent_Pick, dtype: object

In [116]:
Tricks_winp.columns[1]

'[0, 0, 1]'

In [1]:
import os
import numpy as np

In [12]:
# deck_lengths = np.array([0])
path = 'src/Decks/loaded/'

# for file in os.listdir(path): 
#     deck_lengths = np.append(deck_lengths, (len(np.load(path+file))))
#     print(path+file)
#     print(deck_lengths)

In [28]:
len(deck_lengths)

16

In [21]:
np.save('src/deck_lengths.npy', deck_lengths)

In [22]:
np.load('src/deck_lengths.npy')

array([      0,     100,     100, 1000000, 1000000, 1000000, 1000000,
       1000000,  900000, 2000000,  100000,       1,     100,     100,
             1])

In [18]:
deck_lengths

array([      0, 1000000, 1000000, 1000000, 1000000, 2000000,  100000,
        900000, 1000000,     100,     100,     100,       1,     100,
             1,     115])

In [3]:
(np.load('src/Decks/seeds+num_cards/deck_lengths.npy'))

array([      0, 1000000, 1000000, 1000000, 1000000, 2000000,  100000,
        900000, 1000000,     100,     100,     100,       1,     100,
             1,     115,     202])

In [2]:
(np.load('src/Decks/seeds+num_cards/used_seeds.npy'))

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
deck_lengths = np.array([0])
for i in np.load('src/used_seeds.npy')[1:]:
    deck_lengths = np.append(deck_lengths, (len(np.load(path+f'seed_{i}.npy'))))

In [13]:
len(np.load(path+f'seed_{14}.npy'))

115